-- Avaliações pós-atendimento (Supabase/PostgreSQL)
begin;

create extension if not exists pgcrypto;

alter table public.organization_policies
  add column if not exists client_review boolean not null default false,
  add column if not exists review_coupon_id uuid null references public.coupons(id) on delete set null;

create table if not exists public.review_invitations (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  token uuid not null default gen_random_uuid(),
  scheduled_at timestamptz not null,
  sent_at timestamptz,
  status text not null default 'pending' check (status in ('pending', 'processing', 'sent', 'failed', 'submitted')),
  attempts smallint not null default 0 check (attempts between 0 and 10),
  next_retry_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (appointment_id),
  unique (token)
);

create table if not exists public.client_reviews (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  invitation_id bigint not null references public.review_invitations(id) on delete restrict,
  rating smallint not null check (rating between 0 and 5),
  description text check (char_length(description) <= 2000),
  media_url text,
  media_type text check (media_type is null or media_type in ('image', 'video')),
  created_at timestamptz not null default now(),
  unique (appointment_id),
  unique (invitation_id)
);

create index if not exists review_invitations_delivery_idx
  on public.review_invitations (status, scheduled_at, next_retry_at);
create index if not exists client_reviews_organization_idx
  on public.client_reviews (organization_id, created_at desc);
create index if not exists appointments_review_candidates_idx
  on public.appointments (organization_id, appointment_date, status)
  where client_phone is not null;

create or replace function public.get_review_stats(p_organization_id uuid)
returns table (average numeric, total bigint, distribution jsonb)
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(avg(rating), 0)::numeric,
    count(*)::bigint,
    jsonb_build_array(
      count(*) filter (where rating = 0),
      count(*) filter (where rating = 1),
      count(*) filter (where rating = 2),
      count(*) filter (where rating = 3),
      count(*) filter (where rating = 4),
      count(*) filter (where rating = 5)
    )
  from public.client_reviews
  where organization_id = p_organization_id;
$$;

revoke all on function public.get_review_stats(uuid) from public, anon, authenticated;
grant execute on function public.get_review_stats(uuid) to service_role;

alter table public.review_invitations enable row level security;
alter table public.client_reviews enable row level security;

-- O backend usa a service role. Nenhuma leitura/gravação anônima direta é permitida.
revoke all on public.review_invitations from anon, authenticated;
revoke all on public.client_reviews from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'review-media',
  'review-media',
  false,
  26214400,
  array['image/jpeg','image/png','image/webp','video/mp4','video/webm','video/quicktime']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view review media" on storage.objects;

commit;
